### ISSUE TITLE
Can you please clarify how to configure users on okta.com?

### ISSUE THREAD

**Issue by keepitsimple** [authenio/react-samlify#2]
I registered on okta.com and configured it as IdP, but I cannot receive `email` &`login` fields from OKTA.

Can you please make a screenshots how you configured user attributes (or mapping between OKTA & passify) for `passify`?

Thank you in advance!

**Comment by tngan** [comment]
![image](https://user-images.githubusercontent.com/10245912/51082894-e647e180-174a-11e9-8f3e-1ea56317bf1d.png)

**Comment by tngan** [comment]
@keepitsimple You can edit it in `Configure SAML` tab.

![image](https://user-images.githubusercontent.com/10245912/51082901-0d9eae80-174b-11e9-87fe-b4d652b2dc89.png)

**Comment by keepitsimple** [comment]
Thank you so much!

**Comment by tngan** [comment]
@keepitsimple Good to know, have a nice day.
